ShadowBlip/OpenGamepadUI

- core/ui/menu/launch/game_launch_menu.tscn
- core/ui/menu/library/library_menu.gd
- core/ui/menu/library/library_menu.tscn
- core/ui/menu/main-menu/main_menu_container.gd
- core/ui/menu/main-menu/main_menu_container.tscn
- core/ui/menu/navigation/context_bar.tscn
- core/ui/menu/navigation/top_bar.gd
- core/ui/menu/navigation/top_bar.tscn
- core/ui/menu/qam/quick_access_menu.tscn
- core/ui/menu/settings/settings_menu.gd
- core/ui/menu/settings/settings_menu.tscn
- main.tscn
> Modify margins for all menus to allow top bar to be transparent

- addons/godot-evdev/src/device.cpp
- addons/godot-evdev/src/device.h
- addons/godot-evdev/src/event.cpp
- addons/godot-evdev/src/ff.cpp
- addons/godot-evdev/src/ff.h
- addons/godot-evdev/src/register_types.cpp
- addons/godot-evdev/src/virtual_device.cpp
- addons/godot-evdev/src/virtual_device.h
- core/autoload/input_manager.gd
> Implement handling rumble events for virtual gamepads

- core/global/plugin_loader.gd
- core/systems/network/http_image_fetcher.gd
- core/ui/components/plugin_store_item.gd
- core/ui/components/plugin_store_item.tscn
- core/ui/menu/settings/plugin_settings_menu.gd
- core/ui/menu/settings/plugin_store_menu.gd
- entrypoint.gd
- Plugin settings manager will now update when new plugins are installed.
- PluginLoader will now check every 5 minutes and send a signal when a plugin update or a new plugin is available. 
- Plugin store will send a notification that updates are available for installed plugins and when new plugins are available in the store.
> Better Plugin Install

- core/ui/menu/qam/powertools_menu.gd
* Use threading for OS.execute calls, improving UI responsiveness.
* Add function comments
> Pt threading

- core/global/input_manager.gd
- core/main.gd
- core/ui/menu/osk/on_screen_keyboard.gd
> Enable in-game OSK shortcut and X11 key events

- core/global/boxart_manager.gd
- core/global/settings_manager.gd
- core/main.gd
- core/main.tscn
- core/ui/menu/launch/game_boxart_settings.gd
- core/ui/menu/launch/game_boxart_settings.tscn
- core/ui/menu/launch/game_launch_settings.tscn
- core/ui/menu/launch/game_settings.tscn
> Add boxart settings menu

- core/ui/components/slider.tscn
- core/ui/components/toggle.tscn
- core/ui/menu/qam/powertools_menu.gd
- core/ui/menu/qam/powertools_menu.tscn
- rootfs/usr/share/opengamepadui/scripts/powertools
- Add intel iGPU clock control.
- Restructure and rename vars in powertools for consistency and readability. 
- Improve visual appearance of sliders, toggles, and overall powertools menu.
> Add intel iGPU clock control.

- assets/themes/dracula.tres
- core/ui/components/text.gd
- core/ui/components/text.tscn
- core/ui/menu/settings/general_settings_menu.gd
- core/ui/menu/settings/general_settings_menu.tscn
Also adds text focus/highlighting:
> fix(GeneralSettings): add system info to general settings

- core/platform/ayaneo_gen2_gamepad.tres
- core/systems/input/handheld_gamepad.gd
This will help me troubleshoot issues with handhelds I don;t have direct access to. Also fixed the NEXT issue troubleshot by user PacoA.
> fix(HandheldGamepad): Improved logging and AYANEO NEXT buttons

- core/global/platform.gd
- core/platform/onexplayer_gen3.gd
- core/platform/onexplayer_gen3.tres
- core/platform/onexplayer_gen3_gamepad.tres
* Identify OneXPlayer devices by CPU
* Add OneXPlayer Mini Pro
> fix(Platform): Better OneXplayer Platform detection

- addons/controller_icons/Mapper.gd
- core/global/input_manager.gd
- core/global/launch_manager.gd
- core/global/platform.gd
- core/platform/mapped_event.gd
- core/platform/platform_provider.gd
- core/systems/input/focus_group.gd
- core/systems/input/focus_group_setter.gd
- core/systems/input/focus_stack.gd
- core/systems/input/handheld_gamepad.gd
- core/systems/input/managed_gamepad.gd
- core/systems/launcher/running_app.gd
- core/systems/threading/shared_thread.gd
- core/systems/threading/thread_pool.gd
- core/systems/updater/software_updater.gd
- core/ui/card_ui/card_ui.gd
- core/ui/card_ui/navigation/running_game_card.gd
- core/ui/card_ui/qam/qam_card.gd
- core/ui/card_ui_only_qam/qam/quick_access_menu_focus.tres
- core/ui/card_ui_only_qam/settings/settings_menu_focus.tres
- core/ui/components/expandable_card.gd
- core/ui/vapor_ui/gamepad/gamepad_settings.gd
- core/ui/vapor_ui/settings/logging_settings_menu.gd
- core/ui/vapor_ui/vapor_ui.gd
- docs/plugins/TUTORIALS.md
- Use hidden path to process events.
- Support getting event from /dev/input and /dev/input/.hidden
- Reset logger to INFO on all modules.
- Restore input on clean exit.
- Restore input on startup if crashed.
> fix(InputManager): Fix hide/restore event fd's

- core/global/platform.gd
Turns out you actually need to install the new scripts your code relies on.
> fix(platform): Identified GPD issue as PKGBUILD issue. Revert disable.

- core/global/platform.gd
- core/platform/ayaneo_gen3_gamepad.tres
- core/platform/gpd_gen2_gamepad.tres
- core/platform/gpd_gen3_gamepad.tres
- core/systems/input/handheld_gamepad.gd
- Remove on_release for a few events that weren't necessary.
- Add audio buttons for GPD Win4 now that there is a solution for the bugged BIOS.
- Do some error checking earlier in the loop for matching mapped events.
- Make some debug statements more clear.
> fix(platform/HandheldController): HandheldGamepad Tweaks

- assets/state/state_machines/first_boot_network_state_machine.tres
- assets/state/states/first_boot_network_password.tres
- core/systems/input/back_input_handler.gd
- core/ui/card_ui/ootbe/network_select.gd
- core/ui/card_ui/ootbe/network_select.tscn
- core/ui/components/wifi_network_tree.gd
> fix(OOBE): Fix wifi password prompt

- core/platform/chimeraos.gd
- core/platform/steamos.gd
- core/systems/effects/effect.gd
- core/systems/effects/fade_effect.gd
- core/systems/effects/slide_effect.gd
- core/ui/card_ui/card_ui.tscn
- core/ui/card_ui/main-menu/main_menu.tscn
- core/ui/card_ui/navigation/in-game_notification.tscn
- core/ui/card_ui/ootbe/finished_menu.tscn
- core/ui/card_ui/ootbe/language_select.tscn
- core/ui/card_ui/ootbe/network_select.tscn
- core/ui/card_ui/ootbe/plugin_select.tscn
- core/ui/card_ui/ootbe/plugin_setup.tscn
- core/ui/card_ui/power/power_menu.tscn
- core/ui/components/card.gd
- core/ui/components/card.tscn
- core/ui/components/card_button.gd
- core/ui/components/card_icon_button.gd
- core/ui/vapor_ui/osk/on_screen_keyboard.tscn
> fix(Card): add mouse click support

- core/systems/input/managed_gamepad.gd
- core/systems/utility/bitwise.gd
- core/ui/card_ui/home/cardui_home.gd
This change adds "echo events", which are button down events that re-occur when the user is holding down a direction. This only happens in intercept ALL mode.
Fixes  #160
> Add echo input events when holding down a direction

- rootfs/Makefile
10-opengamepadui-handheld.rules was changed to 61-opengamepadui-handheld.rules
> Change Makefile according to udev/rules.d change

- core/systems/effects/raise_effect.gd
- core/ui/components/card.gd
- core/ui/components/card.tscn
> fix(GameCard): use child clipping for rounded edges instead of shader

- core/ui/card_ui/settings/settings_menu.tscn
- core/ui/card_ui_only_qam/settings/settings_menu.tscn
- core/ui/vapor_ui/debug/processes_menu.tscn
- Fix FocusGroup for General menu in only-qam session.
- Fix FocusGroup for Processes menu in only-qam and full session.
> fix(SettingsMenu): Fix focus on general menu in only-qam session and processess menu in only-qam and full session.

- core/global/install_manager.gd
- core/global/library_manager.gd
- core/systems/launcher/interactive_process.gd
- core/systems/library/library.gd
- core/systems/library/library_item.gd
- core/ui/card_ui/card_ui.gd
- core/ui/card_ui/card_ui.tscn
- core/ui/card_ui/home/cardui_home.gd
- core/ui/card_ui/library/library_menu.gd
This change does some cleanup and refactoring of how we handle library changes. This _should_ create a more reactive experience and remove deprecated code.
> Refactor Library Menus for better library management

- core/global/platform.gd
Previous change moved detecting CPU and GPU until after the platform was detected to support ROG Ally thermal throttle profile support discovery. Intel and AMD OXP's have the same DMI information and rely on knowing the CPU vendor. This moves the CPU/GPU detect back to before the platform detect and moves the thermal policy check to after loading the ROG Ally platform.
> fix(platform): Fix OXP Gen1 and Gen2 detection

- core/systems/power/power_saver.gd
- core/ui/card_ui/card_ui.gd
- project.godot
> feat(PowerSaver): decrease FPS when idle and use low processor mode

- core/ui/vapor_ui/qam/performance_menu.tscn
- core/ui/vapor_ui/qam/quick_settings_menu.tscn
This PR removes the useless "per-game" toggle in the QAM.
> fix(QAM): remove per-game toggle

- core/global/platform.gd
- core/platform/handheld/ayn/ayn_gen1.tres
- core/platform/handheld/ayn/ayn_gen2.tres
- core/platform/handheld/ayn/ayn_gen3.tres
While at it, add a newly discovered key combo to previous ayn devices.
> fix(Platform): Add Ayn Loki MiniPro platform.

- core/global/gamescope.gd
- core/ui/card_ui/card_ui.gd
> fix(Gamescope): only blur if there is a valid focused GFX app

- core/ui/card_ui/card_ui.tscn
- core/ui/vapor_ui/osk/on_screen_keyboard.gd
- core/ui/vapor_ui/osk/on_screen_keyboard.tscn
This change adds fade+slide animations on the OSK
> feat(OSK): add open animation

- core/global/launch_manager.gd
- core/ui/card_ui/launch/game_settings.tscn
- core/ui/vapor_ui/launch/game_launch_settings.gd
- core/ui/vapor_ui/launch/game_launch_settings.tscn
> feat(Sandbox): add per-game toggle to enable/disable sandboxing

- core/systems/hardware/hardware_manager.gd
> fix(HardwareManager): skip unidentified/unsupported GPU cards

- core/systems/launcher/reaper.gd
- core/systems/launcher/running_app.gd
- core/systems/threading/linuxthread_test.gd
Updates godot-linuxthread with subreaper feature and updates Reaper class to use it for spawning processes.
> fix(Reaper): use subreaper to spawn processes for better process discovery

- Makefile
- docker/Dockerfile
- docs/install/deck_install_script.sh
This change updates the `Makefile` systemd-sysext build target to include gamescope-session in the archive. Related to:
https://github.com/ShadowBlip/OpenGamepadUI-session/pull/8
Fixes #265
> chore(Makefile): update systemd-sysext build with new gamescope-session dependency

- .releaserc.yaml
- Makefile
- docker/Dockerfile
- package/rpm/opengamepadui.spec
- rootfs/Makefile
- rootfs/usr/bin/opengamepadui
- rootfs/usr/share/opengamepadui/scripts/make_nice
- rootfs/usr/share/opengamepadui/scripts/manage_input
- rootfs/usr/share/opengamepadui/scripts/powertools
This change adds building of RPM packages of OpenGamepadUI and makes some small modifications to some scripts to make them compatible with Fedora.
> chore(Packaging): add Fedora-compatible RPM builds

- .github/workflows/docker.yaml
- .github/workflows/test.yaml
- docker/Dockerfile
This change will pin the version of Godot in the container builder image.
> chore(CI): pin Godot Engine version in container image

- project.godot
> fix(Renderer): update to using the Vulkan renderer by default

- core/systems/input/gamepad_manager.gd
Re-adds improvements to virtual device detection without hiding removed.
> fix(GamepadManager): Properly detect virtual devices.

- core/global/platform.gd
- core/platform/handheld/asus/rog_ally_gen1.gd
- core/platform/handheld/asus/rog_ally_gen1.tres
- Detect board_name revision for newer ROG Ally.
- Adjust keymap for ROG Ally to align with hid-asus.
> fix(Platform): Support asus-hid patches.

- Makefile
> chore(Makefile): make EXPORT_TEMPLATE variable user configurable

- core/platform/os/manjaro.gd
This will enable switching to Desktop mode, similar as we have for ChimeraOS platform. Already tested on my end.
> fix(Platform): update platform for Manjaro

- assets/locale/Makefile
- assets/locale/zh_CH.po
- project.godot
Additional translation help from @KatyushaScarlet
> chore(locale): Add Chinese language localization.

- assets/gamepad/icon_mappings/ps4.tres
- assets/gamepad/icon_mappings/ps5.tres
- assets/gamepad/icon_mappings/switch.tres
> Add mappings for PS4 controller

- core/systems/state/visibility_manager.gd
This change fixes issues where some menus can be seen in the background that shouldn't be visible when opening menus like the Quick Bar and Power Menu. The Visibility Manager will now look at the state stack to see if it should remain visible during certain states.
> fix(Visibility): fix cases where menus are visible in the background when they shouldn't be

- core/systems/input/overlay_mode_input_manager.gd
- core/ui/components/dropdown.gd
- project.godot
- Adds Steam chords for screenshot and capture video.
- Consolidates some chord specific functions into a single function.
- Overlay mode will use its own ogui_* events t o avoid conflicts with normal mode.
> fix(Overlay Mode): Prevent extra guide events in overlay mode.

- assets/gamepad/icon_mappings/xbox360.tres
- assets/gamepad/icon_mappings/xboxone.tres
- core/systems/input/input_plumber_profile.gd
- core/ui/card_ui/gamepad/gamepad_settings.gd
Requires https://github.com/ShadowBlip/InputPlumber/pull/135 to be merged
> fix(Target Device): Update target devices to latest InputPlumber version.

- assets/locale/zh_CH.po
> chore(locale): update chinese localization

- core/platform/hardware/dmi_overrides_apu_database.tres
- core/systems/hardware/hardware_manager.gd
- Adds new APU dattabase where the Model Name matches  entry.
- Simplifies how APU features are detected.
Fixes #318
> fix(APU Database): Add ability to override APUEntry using DMI data.

- assets/gamepad/profiles/default.json
- core/systems/input/input_plumber_profile.gd
- core/ui/card_ui/gamepad/gamepad_settings.gd
- Also remove paddle mappings.
> fix(SteamDeck Target): Reenable SteamDeck target device.

- .gitmodules
- .releaserc.yaml
- Makefile
- addons/.gitignore
- addons/dbus/dbus.gdextension
- addons/linuxthread/linuxthread.gdextension
- addons/pty/pty.gdextension
- addons/unixsock/unixsock.gdextension
- addons/xlib/xlib.gdextension
- core/systems/hardware/hardware_manager.gd
- core/systems/input/input_plumber.gd
- core/systems/utility/xdg.gd
- docker/Dockerfile.addons
- export_presets.cfg
- gdext/.gitignore
- gdext/Makefile
- gdext/SConstruct
- package/rpm/opengamepadui.spec
- rootfs/Makefile
Fixes  #382
This change re-adds the GDExtension sources back as submodules so they can be built easily from source. It includes a custom SConstruct for building all extensions at once to prevent duplicate compilation of godot-cpp.
> fix(GDExt): add gdextension module source

- entrypoint.gd
This change fixes this error on startup:
> fix(Entrypoint): defer add child scene

- core/ui/card_ui/library/library_menu.tscn
- core/ui/components/card.tscn
Update spacing for card items in library:
Old:
New:
> fix(Library): update card spacing

- core/ui/card_ui/card_ui.gd
- extensions/core/src/dbus/inputplumber/input_manager.rs
- extensions/core/src/input/inputplumber.rs
We missed adding this after the core refactor :sweat_smile:
> fix(Input): enable InputPlumber management of all supported devices in full session

- core/systems/input/input_manager.gd
This change fixes button combos in the full session by tracking the button pressed state if InputPlumber is running to determine if a button combo is happening.
> fix(Gamepad): fix button combos used via InputPlumber

- .github/workflows/release.yaml
- .releaserc.yaml
- Makefile
- package/archlinux/PKGBUILD
This change updates CI steps to automatically publish the release to AUR upon release.
> chore(CI): add step to publish release to AUR

- extensions/Cargo.lock
- extensions/core/Cargo.toml
- extensions/core/src/vdf.rs
Updates dependencies for core engine extensions.
> fix: update core extension dependencies

- core/global/platform.gd
- core/platform/os/bazzite.gd
- core/platform/os/bazzite.gd.uid
- core/platform/os/bazzite.tres
This PR adds an initial changes so OGUI can recognize Bazzite as a proper operating system. For now it adds "Switch to Desktop" button, same as in ChimeraOS. I also wanted to change boot animation to one that Bazzite uses for Steam Gaming Mode, but I'm so new to Godot development in general, so for now that's the least I can do.
> feat(Platform): add Bazzite
