ShadowBlip/OpenGamepadUI

core/only_qam.gd, core/systems/input/handheld_gamepad.gd, core/ui/menu/qam/powertools_menu.gd
PowerTools:
- Use global ThreadGroup instead of ThreadGroup.new()
- Use timer override to reduce number of threaded calls to only the necessary ones.
- Only use threading to set most values, do read synchronously. 
Only QAM mode:
- Use overlay instead of external_overlay. Improves responsiveness of OGUI QAM while in Steam's GamepadUI. Also solves MangoHud not displaying when OGUI QAM is visible.
=> Performance Fixes

core/only_qam.gd, core/systems/launcher/interactive_process.gd
Move OGUI Steam from OS call to InteractiveProcess to facilitate the following:
- Output steam's stdout to $HOME/.steam-stdout.log for cleaner .ogui-stdout.log and for consistency with other sessions.
This is currently only partially working ATT. Steam's stdout does go to the correct file location, but the buffer seams to only load in waves and truncates frequently. It cannot be used in this state for debug tracking for steam issues.
=> Move OGUI Steam from OS call to InteractiveProcess

core/ui/menu/qam/powertools_menu.gd
Adds support for the R1000 series of APU's from AMD, like the one found in the Atari VCS.
TDP specs taken from here: https://www.amd.com/en/products/embedded-ryzen-r1000-series
=> Add R1000 series APU's

core/systems/input/focus_manager.gd, core/systems/input/focus_manager.tscn, core/ui/components/plugin_store_item.tscn, core/ui/menu/settings/plugin_store_menu.tscn
This will fix some of the focusing issues we've seen, but I think we should consider refactoring how we handle focus in the future. I think implementing something like a `FocusTree`, which tracks the flow of input focus would better.
=> fix(FocusManager): add 'intercept_children_only' option to only intercept back input if a child has focus

core/global/platform.gd, core/platform/hardware/amd_apu_database.tres, core/platform/hardware/apu_database.gd, core/platform/hardware/apu_entry.gd, core/platform/hardware/intel_apu_database.tres, core/ui/menu/qam/powertools_menu.gd, core/ui/menu/settings/general_settings_menu.gd, core/ui/menu/settings/general_settings_menu.tscn
* Adds APUDatabase resource, replaces the dictionary in powertools.
* Adds APUEntry resource. Outlines TDP settings for an APU by model.
* Adds CPUInfo and GPUInfo data classes to store relevant capabilities of a given CPU/GPU
* Powertools now loads data from Platform on the CPU and GPU
* Add CPU and GPU model display to general settings menu.
=> feat(platform): Use platform for hardware detect.

core/global/input_manager.gd, core/global/platform.gd, core/systems/input/handheld_gamepad.gd
* Fix incorrect platform for AOKZOE A1
* Fix orphaned_gamepad array being modified outside of mutex.lock()
* Fix bug where a device who's gamepad event was read before the keyboard device could fail to open properly.
=> fix(Platform): Fix AOKZOE A1 support

entrypoint.gd
Loading a `.tres` resource caches it so it only loads once. When applying a resource pack, we want to clear that cache so it uses the resource from the pack and not the cached one.
=> fix(Entrypoint): reload version.tres and replace its cache entry after loading update packs

core/systems/launcher/running_app.gd
This change will now let OGUI detect when a Steam game has closed and we need to shut down Steam.
=> fix(RunningApp): check to see if the running app's window still exists

core/ui/menu/qam/only_quick_access_menu.tscn, core/ui/menu/qam/performance_menu.gd, core/ui/menu/qam/powertools_menu.gd, core/ui/menu/qam/powertools_menu.tscn, core/ui/menu/qam/quick_access_menu.tscn, core/ui/menu/qam/quick_settings_menu.gd
* Use Notifications and Quick settings in Only QAM mode
* Use command delay for setting slider in quick settings and performance menu's, reducing UI hangups due to excessive calls.
* Minor text improvements in Powertools.tscn
=> fix(QAM): General QAM improvements

core/systems/threading/shared_thread.gd, core/systems/threading/thread_pool.gd, core/systems/threading/thread_pool.tres, core/systems/threading/thread_pool_test.gd, core/systems/threading/thread_pool_test.tscn, core/systems/threading/watchdog_thread.gd
This PR adds the `ThreadPool` class and shared resource which allows you to execute methods in a separate available thread. By default, a thread pool is created with a number of threads equal to the CPU core count. Each thread waits for tasks to be queued by `ThreadPool.exec()`. When a task is queued, one of the threads from the pool will wake up and begin processing the task until it is completed.
Example:
```gdscript
var thread_pool := load("res://core/systems/threading/thread_pool.tres")
thread_pool.start()
var output = await thread_pool.exec(my_func)
```
=> fix(threading): Add thread deconstructor and ThreadPool

rootfs/usr/lib/udev/hwdb.d/59-opengamepadui-handheld.hwdb, rootfs/usr/lib/udev/rules.d/10-opengamepadui-handheld.rules, rootfs/usr/lib/udev/rules.d/61-opengamepadui-handheld.rules
This is a better method of adding uaccess to keyboard/mouse type devices. This new method does the following:
- No longer has collisions with other ID_INPUT_JOYSTICK rules that could cause keyboard devices to trigger looping sleep/wake cycles.
- No longer adds excessive and unnecessary input device event codes.
=> fix(InputManager): Use FORCE_INPUT_UACCESS

core/global/input_manager.gd, core/systems/input/handheld_gamepad.gd, core/ui/only_qam_ui/only_qam_main.gd, rootfs/usr/share/opengamepadui/scripts/manage_input, rootfs/usr/share/polkit-1/actions/org.shadowblip.manage_input.policy
Use fd moving instead of sandboxing for only-qam, solved the following issues:
- pkexec no longer fails in only-qam mode
- Inputs connected after bootup lo longer fail to discover or create duplicate input.
- Sandbox no longer required to hide input devices with uaccess in --only-qam
=> fix(only-qam): Use fd moving instead of sandboxing

core/main.gd, core/systems/debug/log.gd, core/systems/debug/log_manager.gd, core/systems/input/focus_group.gd, core/systems/state/state_machine.gd, core/ui/vapor_ui/settings/logging_settings_menu.gd
Users can now add `LOG_LEVEL=<level>` (debug, info, warn, error) and/or `LOG_LEVEL_<NAME>=<level>` to turn on/off log levels using an environment variable.
If users are using opengamepadui-session, they can export these variables in `~/.config/environment.d/opengamepadui-session.conf`.
Example:
```bash
export LOG_LEVEL=info
export LOG_LEVEL_FOCUSGROUP=debug
export LOG_LEVEL_INPUTMANAGER=debug
```
=> fix(logging): Add LOG_LEVEL env var to set log level

core/global/platform.gd
Temporary workaround until I can figure out why GPD devices crash.
=> fix(platform): Disable GPD HandeheldController/Platform detection as it causes boot loops with the new logic.

core/global/library_manager.gd, core/systems/input/focus_group.gd, core/ui/card_ui/home/cardui_home.gd, core/ui/card_ui/library/library_menu.gd, core/ui/components/card.gd
This change adds a `set_library_item()` method to `GameCard` which will listen for signals when a library item is removed and automatically free itself. This provides better live library reloading.
Fixes #34
=> Better Library hot-reloading

core/ui/vapor_ui/osk/on_screen_keyboard.gd
=> fix(OSK): add joypad icons for keyboard shortcuts

rootfs/usr/share/opengamepadui/scripts/powertools
- Fixes GPU Clock not getting set when changing mix/max settings.
=> fix(PowerTools): Add commit write and reset to amdgpuclock changes.

core/systems/launcher/running_app.gd, core/ui/card_ui/navigation/running_game_card.gd, core/ui/card_ui/navigation/running_game_card.tscn
This adds buttons in the running game card in the main menu that allows users to switch between multiple windows from a single app.
=> feat(RunningApp): add window switching within a given app

core/ui/vapor_ui/qam/powertools_menu.gd, rootfs/usr/share/opengamepadui/scripts/powertools
This PR should be merged after we find a fix for FocusManager on a non visible node or the PT menu will break completely.
- Fix GPUCLK setting properly for AMD GPU's.
- Fix GPUCLK setting properly for Intel GPU's.
- Fix manual/auto toggle for writing to performance mode for AMDPGU's.
- Disable core count select when SMT is disabled.
- Fix SMT toggle setting too few cores on some CPU's when toggled.
- Fix CPU Boost toggle appearing when using amd_pstate driver, as the sysfs character file to toggle boost is not present using that governor.
=> fix(PowerTools): Fix multiple PowerTools functions

assets/themes/card_ui-darksoul.tres, assets/themes/card_ui-dracula.tres, core/ui/card_ui/settings/general_settings_menu.gd, core/ui/card_ui/settings/general_settings_menu.tscn
Users can now add their own themes under `~/.local/share/opengamepadui/themes`:
=> fix(Themes): allow users to select themes from 'user://themes'

core/systems/input/managed_gamepad.gd
Identified 2 issues that this PR solves:
- Hall effect joysticks are more precise than analog sticks, which can frequently lead to a delta > .35 when snapping back to 0. The old method rejected all 0 inputs and could lead to a permanently stuck "on" echo event.
- Checking for just the event code ignores event type, which led to many false positives and the need to reject 0 events.. By matching to get_code_name instead of get_code the type is included and false positives are removed. This removes the need to check if the value is 0 as the false 0's from EV_RESERVED are no longer present. This also eliminates false positives from some SYN events and ABS_Y
=> fix(ManagedGamepad): Fix echo input bugs using hall effect joysticks.

assets/state/states/help_menu.tres, core/ui/card_ui/card_ui.tscn, core/ui/card_ui/help/help_menu.gd, core/ui/card_ui/help/help_menu.tscn, core/ui/card_ui/navigation/top_button_menu.tscn, core/ui/card_ui/qam/quick_access_menu.tscn, core/ui/components/shortcut_button_icon.gd, core/ui/components/shortcut_button_icon.tscn
This change adds a help menu with interface shortcuts.
=> feat(HelpMenu): Add help menu with interface shortcuts

.releaserc.yaml, Makefile, core/systems/crypto/package_verifier.gd, core/systems/updater/software_updater.gd, entrypoint.gd
This change refactors the update system to use full binary archives instead of using Godot resource packs. This has some advantages:
* It allows updates to include new GDExtension native libraries when using the updater.
* It allows updates to use a newer Godot Engine build of OpenGamepadUI.
* It resolves some bugs we've seen with resource packs where the class definitions are not parsed correctly.
The new update system includes a way to create an "update zip" when you run `make dist-update-zip`. Invoking this target will build the project and create a `metadata.json` file with the hashes and signatures of all files in the update and zip them up.
When OpenGamepadUI launches, it looks for an update in `~/.local/share/opengamepadui/updates/update.zip`. If it finds one, it will read the …
=> Refactor update system to launch full binary updates

core/global/platform.gd, core/platform/ally_gen1.gd, core/platform/ally_gen1.tres, core/platform/ally_gen1_gamepad.tres, core/platform/hardware/amd_apu_database.tres, core/systems/input/handheld_gamepad.gd, core/ui/vapor_ui/qam/powertools_menu.gd, core/ui/vapor_ui/qam/powertools_menu.tscn, rootfs/usr/lib/udev/hwdb.d/59-opengamepadui-handheld.hwdb, rootfs/usr/share/opengamepadui/scripts/powertools
- Adds ROG Platform.
- Adds Z1 Extreme APU.
- Adds Ryzen 7 7840U APU.
- Adds Thermal Profile Selector for ASUS devices with the thermal profile file descriptor.
- APU's that cannot read `ryzenadj -i` will be set to the midpoint of their operational range when starting up. This ensures the UI reflects a known value.
- Fix bug in HandheldController where a macro that had an up and down event in the same frame would cancel each other out.
=> fix(Platform): Add ROG Ally

core/ui/card_ui/ootbe/plugin_setup.gd
This fixes the issue where the first boot menu is blank if no plugins are selected.
=> fix(OOTBE): fix bug where first boot menu would be empty after selecting no plugins

core/ui/card_ui/ootbe/plugin_setup.gd, core/ui/card_ui/power/power_menu.gd, core/ui/card_ui/power/power_menu.tscn, project.godot
This is related to #211 where the Vulkan renderer on Godot v4.1 causes hanging issues on some hardware. This change updates the default renderer to use OpenGL until a future engine version fixes the issues we've seen with the Vulkan renderer.
=> fix(Renderer): update to using OpenGL renderer by default for compatibility

core/global/library_manager.gd, core/ui/card_ui/home/cardui_home.gd, core/ui/card_ui/home/cardui_home.tscn, core/ui/components/library_banner.gd, core/ui/components/library_banner.tscn, core/ui/components/library_deck.gd, core/ui/components/library_deck.tscn
This change adds a library banner when the library deck is focused on the home menu:
=> Add home menu banner showing games from library when library deck is focused

core/platform/actions/start_opensd.gd
Closes #236
This change uses v1.0.2 of [godot-opensd](https://github.com/ShadowBlip/godot-opensd/), which does not statically link glibc. It now targets an older version of glibc to provide better compatibility with different platforms.
=> fix(SteamDeck): use godot-opensd v1.0.2 which links against a more compatible version of glibc

core/systems/performance/performance_manager.gd, core/systems/threading/utility_thread.tres, core/ui/common/qam/powertools_menu.gd, core/ui/common/qam/powertools_menu.tscn
- Fix issue where thread_pool would call certain functions out of roder, causing the UI to desync from the actual hardware status.
- Fix issue when ryzenadj cannot read the mapped memory table causing the system to be set to an extremely low power state.
- Fix issue where PowerTools menu would become visible before the profile was applied and a changed setting woudl apply bad values to the profile for everything not yet loaded.
=> fix(PerformanceManager): Fix bugs with PerformanceManager.

core/global/platform.gd, core/systems/performance/performance_manager.gd, core/systems/performance/performance_profile.gd, core/ui/common/qam/powertools_menu.gd
- Use profile.var instead of var for profile related variables.
- Synchronize initial loading flow using signals.
- Simplify some functions for AMDGPU clock reading.
=> fix(PerformanceManager): Optimize PerformanceManager

core/global/platform.gd, core/systems/performance/performance_manager.gd, core/ui/common/qam/powertools_menu.gd, rootfs/usr/share/opengamepadui/scripts/powertools
- Update powertools script to use cardX in /sys/class/drm passed from PerformanceManager.
- Update Plaform to detect all cards in the system. We default to the first entry for simplicity in this hotfix but we need to find a way to link the pci data to the devices in vulkaninfo.
- Update Platform to use native methods of determining the current display device vendor, model, and driver.
- Fix bug in PowerTools menu that would cause GPU clocks to be set to 200Mhz on startup and override that value in the profile.
- Fix Intel TDP and GPUCLK settings.
=> fix(PerformanceManager): Fix regression in hard coding card0 for gpu settings.

core/systems/hardware/drm_card_info.gd, core/systems/hardware/drm_card_port.gd, core/systems/hardware/hardware_manager.gd, core/systems/hardware/hardware_manager_test.gd, core/systems/hardware/hardware_manager_test.tscn
We never actually tested that signals on GPU port changes were working. This change fixes that, adds a test, and includes a `start_gpu_watch()` method to poll for GPU state changes in a thread.
=> fix(HardwareManager): fix GPU port signals and add test

assets/state/states/settings_general_controller.tres, core/global/launch_manager.gd, core/systems/input/gamepad_manager.gd, core/systems/input/managed_gamepad.gd, core/systems/input/managed_gamepad_test.gd, core/ui/card_ui/settings/general_controller_settings_menu.gd, core/ui/card_ui/settings/general_controller_settings_menu.tscn, core/ui/card_ui/settings/settings_menu.tscn, core/ui/card_ui_overlay_mode/card_ui_overlay_mode.gd, core/ui/components/toggle.tscn
- Adds support for Playstation controllers to be detected/managed by GamepadManager. #260
- Adds support for x/y axes who's range starts at 0 and have a positive value midpoint. 
- Replaces DeviceHider with SDL_JOYSTICK_HIDAPI environment variable.
- Adds general controllers settings menu. 
- Bug Fix: Launching Steam in overlay mode will no longer hold up the main thread.
- Adds GUT test for normalized axes.
=> feat(GamepadManager): Add support for Dualsense/Dualshock controllers

core/platform/handheld/ayaneo/ayaneo_gen2.tres
The alternate keys were duplicated and "make unique" wasn't making unique resources, so changing one would change the other. Deleted the alternate keys and remade them from scratch.
=> fix(Platform): Fix alternate key combos for aya_gen2.

Makefile
On some Godot versions for different Linux distros, the old version matching pattern was returning the wrong results. This should make determining the Godot version more robust so we can download the appropriate export templates.
=> chore(Makefile): update Makefile to use a more robust way of detecting godot version and release

Makefile, core/global/launch_manager.gd
This change changes how we set the `STEAM_OVERLAY` atom while games are running. I found that there can be a drastic performance hit on low-spec devices if `STEAM_OVERLAY` is set to `1` while the game is running, so we now set `STEAM_OVERLAY` to `0` unless the user opens up a menu. On the Loki Zero, I saw a 2x performance improvement.
=> fix(LaunchManager): disable STEAM_OVERLAY while game is running and overlay is not focused for performance-sensitive devices

Makefile
Respect GODOT variable for version / release determination
In Gentoo the godot binary is installed in /usr/bin/godot4 because can be insalled with godot3 at the same time.
Using `GODOT=/usr/bin/godot4 make` I seen two error messages abount godot not found.
This PR fixes the custom named godot usage.
=> Custom godot fix

core/ui/card_ui/quick_bar/qb_card.gd, core/ui/components/expandable_card.gd
This change fixes a bug where Quick Bar Menu cards will remain expanded when it is re-opened.
=> fix(ExpandableCard): reset expansion where element visibility is lost

Makefile, core/platform/actions/start_inputplumber.gd, core/platform/actions/start_powerstation.gd, core/platform/handheld/steamdeck/steamdeck.tres, docs/install/deck_install_script.sh, rootfs/usr/lib/systemd/user/systemd-sysext-updater.service, rootfs/usr/share/opengamepadui/scripts/manage_input, rootfs/usr/share/opengamepadui/scripts/update_systemd_ext.sh
This change fixes issues with the systemd extension and updater service. It now includes InputPlumber (and dependencies), as well as platform actions to start InputPlumber and PowerStation.
Fixes #303
=> fix(SystemdExt): update systemd-ext to include inputplumber dependencies

assets/state/state_machines/first_boot_network_state_machine.tres, assets/state/state_machines/first_boot_state_machine.tres, assets/state/state_machines/game_settings_state_machine.tres, assets/state/state_machines/gamepad_settings_state_machine.tres, assets/state/state_machines/plugin_settings_state_machine.tres, assets/state/state_machines/quick_bar_state_machine.tres, assets/state/state_machines/settings_state_machine.tres, core/global/launch_manager.gd, core/systems/input/back_input_handler.gd, core/systems/input/overlay_mode_input_manager.gd, core/systems/state/state_machine.gd, core/systems/state/state_machine_test.gd, core/systems/state/state_updater_test.gd, core/systems/state/state_watcher_test.gd, core/ui/card_ui/main-menu/main_menu_test.gd, core/ui/card_ui_overlay_mode/card_ui_overlay_mode.gd
- Adds `@export var minimum_states: int = 1` to StateMachine. state_machine.pop_state() will never go below this value.
- Sets all non-global StateMachines minimum states to 0.
- Remove code no longer needed in overlay_input_manager that prevented dropping to null states.
- While at it, change method comments in StateMachine to be used in automatic documentation formatting.
=> fix(StateMachine): Prevent global state stack from going null.

core/ui/common/quick_bar/powertools_menu.gd
Sometimes teh values for the sliders will be received with a small arithmetic error (e.g. 15.0000000001). As the sliders take a float, we should round the values to prevent tiny increments from being displayed.
=> fix(PowerTools): Prevent display of floats in UI

project.godot
Thinking about it more, I think having limited input mappings for when InputPlumber is not running (or does not support a specific controller) is nice to have. This partially reverts https://github.com/ShadowBlip/OpenGamepadUI/commit/e62e2964f11705a353937c6b8fde92c784e414a4 but just adds `South`, `East`, and `Guide` to avoid the original issue with https://github.com/godotengine/godot/issues/87112
=> fix(Input): add limited input mappings when not running InputPlumber

core/systems/input/input_plumber.gd, core/systems/threading/shared_thread.gd, project.godot
Fixes #374
This change adds a task that will monitor the running state of InputPlumber. If InputPlumber is running, it disables the Godot input map and relies solely on InputPlumber for gamepad input. If InputPlumber is stopped, it restores the Godot input map so input can be processed by Godot's input system instead.
=> fix(Input): disable/enable Godot input based on InputPlumber running

core/systems/threading/shared_thread.gd, core/ui/card_ui/gamepad/gamepad_settings.gd
This change also removes tracking the method name in `SharedThread` to stop these spam errors:
=> Fix gamepad settings null string assignment

core/ui/components/tabs_header.gd
=> fix(Tabs Container): remove old refs to LB/RB textures

core/ui/card_ui/quick_bar/qb_card.gd, core/ui/card_ui/quick_bar/qb_card.tscn, core/ui/card_ui/settings/general_settings_menu.gd, core/ui/components/card_button.gd
This change adds support for mouse/touch input for expanding and collapsing menu cards and allows mouse input for card buttons.
=> fix(Mouse): add better support for mouse/touch for buttons and menu cards

core/systems/library/library_desktop.gd
This change gracefully handles cases where file access reads may fail when reading desktop file entries.
=> fix(Library): handle bad file open for invalid desktop entries

core/ui/card_ui/settings/general_controller_settings_menu.gd, core/ui/card_ui/settings/general_controller_settings_menu.tscn
This change adds support for using mouse or keyboard input to open the gamepad settings.
=> fix(Gamepad Settings): add mouse handling for gamepad settings button

core/global/install_manager.gd, core/systems/library/library.gd, core/ui/card_ui/launch/game_launch_menu.gd, core/ui/card_ui/launch/game_launch_menu.tscn, core/ui/components/dropdown.tscn, core/ui/components/install_location_card.gd, core/ui/components/install_location_card.gd.uid, core/ui/components/install_location_card.tscn, core/ui/components/install_location_dialog.gd, core/ui/components/install_location_dialog.gd.uid, core/ui/components/install_location_dialog.tscn, core/ui/components/install_options_dialog.gd, core/ui/components/install_options_dialog.gd.uid, core/ui/components/install_options_dialog.tscn
This change adds a new method to the `Library` class to install a library item to a specified location and with arbitrary install options. It also includes new menus to select the install location and options:
Fixes #97
=> feat(Library): add interface and menus to select install location

project.godot
This change removes backspace as a mapping for `ogui_back` to allow keyboard users to press backspace in text boxes without triggering the back action.
=> fix(TextInput): remove backspace from 'ogui_back' event

rootfs/usr/bin/opengamepadui
This change updates the launch script to use the `-e` (`--steam`) argument when launching opengamepadui.
=> fix(Launch Script): use '-e' argument for gamescope

core/platform/os/nixos.gd, core/ui/card_ui/settings/general_settings_menu.tscn, core/ui/card_ui/settings/settings_menu.tscn, project.godot, rootfs/Makefile, rootfs/usr/share/polkit-1/actions/org.shadowblip.nixos_updater.policy
This change updates the NixOS platform class to add a NixOS-specific OS updater to the general settings menu. This updater will only be available if it detects the OS update script provided here:
https://gitlab.com/shadowapex/os-flake/-/blob/main/modules/updater/default.nix?ref_type=heads
=> feat(NixOS): add OS update interface for NixOS

core/ui/common/settings/display_settings_menu.tscn, core/ui/components/battery_container.gd, core/ui/components/slider.gd
This change adds an option for sliders to show the decimal value or not (defaults to `false`). This is now required due to changes in Godot 4.4 which includes the decimal value by default when converting floats to strings.
=> fix(Slider): add option to show/hide decimal values in sliders

core/ui/card_ui/settings/library_settings_menu.gd, core/ui/card_ui/settings/library_settings_menu.tscn
This change adds a new "Enable Desktop Library" toggle in the library settings menu to allow users to enable/disable the built-in local library provider.
=> feat(Library): add toggle to enable/disable local library discovery

core/systems/state/tab_container_state.gd, core/ui/card_ui/library/library_menu.gd, core/ui/card_ui/navigation/search_bar_menu.tscn, core/ui/components/containers/enhanced_scroll_container.gd, core/ui/components/containers/enhanced_scroll_container.gd.uid, core/ui/components/tabs_header.gd, core/ui/components/tabs_header.tscn
This change adds methods for adding/removing tabs to the `TabContainerState` class, making it simpler to add/remove tabs:
Tabs can be added via code like this:
```gdscript
var my_category_tab_node := ScrollContainer.new()
my_category_tab_node.name = "MyCategory"
var tabs_state := load("res://core/ui/card_ui/library/library_tabs_state.tres") as TabContainerState
tabs_state.add_tab("MyCategory", my_category_tab_node)
```
=> feat(Tabs): add methods for adding/removing tabs and add tab scrolling

core/systems/network/http_api_client.gd
This change adds an option to the `HttpApiClient` to allow connecting to servers with invalid TLS settings.
=> fix(HttpApiClient): add option to ignore TLS errors

core/ui/card_ui_overlay_mode/card_ui_overlay_mode.gd
This change enabled inputplumber management of all gamepads in overlay mode. This was previously disabled due to some issues hiding the source gamepads with some external controllers, but this seems to be fixed in newer versions of InputPlumber.
=> fix(Overlay Mode): enable inputplumber management of all gamepads

core/global/launch_manager.gd, core/systems/input/input_plumber.gd, core/systems/input/input_plumber_profile.gd, core/ui/card_ui/gamepad/gamepad_settings.gd
- Adds Horipad Steam Controller as a new additional target.
- Switch to using deck-uhid target over the deck-vchi target
=> feat(Input Devices): Add updated target devices

extensions/Cargo.lock, extensions/core/Cargo.toml, extensions/core/src/resource/resource_processor.rs
This change updates all the Rust dependencies for the core engine extensions. One noticable update is Godot Rust v0.3.1, which has a lot of great new features like async/await and strongly type signals:
https://godot-rust.github.io/dev/may-2025-update/
=> fix(Extensions): update dependencies for core extensions

core/ui/card_ui/card_ui.gd
This change updates the full session to set the baselayer app on startup, which is now required for Gamescope v3.16.3+.
=> fix(Gamescope): set baselayer app at startup

core/platform/os/nixos.gd, core/ui/components/dropdown.tscn
This change adds a dropdown in the update section of the settings menu for NixOS platforms that allows users to select the OS branch to use for updates.
=> fix(NixOS): add OS update branch selector

core/systems/power/power_saver.gd, core/systems/power/power_saver.tscn, core/ui/card_ui/card_ui.tscn, extensions/core/src/gamescope/x11_client.rs
This change moves the `PowerSaver` node, which manages screen dimming and suspend after inactivity, to the bottom of the scene tree in order to process gamepad inputs before anything else.
In Godot, the scene tree processes inputs in this order (https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html#how-does-it-work):
> [!NOTE]
> This should resolve issues with gamepad input, but it's possible that the `PowerSaver` will not see any input events if a user is playing a game using only using a mouse and keyboard. To resolve this, we use the `GAMESCOPE_INPUT_COUNTER` gamescope property to monitor how long ago mouse/keyboard activity happened.
Fixes #471
=> fix(Power Saver): move node to bottom of scene tree to process inputs first

core/global/launch_manager.gd, core/global/plugin_loader.gd, core/systems/launcher/app_lifecycle_hook.gd, core/systems/launcher/reaper.gd, core/systems/launcher/running_app.gd, core/ui/card_ui/card_ui.gd, core/ui/card_ui/navigation/running_game_card.gd, core/ui/common/game/game_loading.gd, core/ui/common/game/game_loading.tscn, extensions/Cargo.lock, extensions/core/src/gamescope.rs, extensions/core/src/gamescope/x11_client.rs, package/nix/package.nix
This change adds a new "Application Lifecycle Hooks" feature that can allow library plugins to hook into different parts of the application launch process, allowing plugins to execute code before or after an application launches. This can be useful for things like pre-compiling shaders, starting a service, downloading dependencies, etc.
These lifecycle hooks also have a mechanism to emit text or progress that can be displayed when a game is launching:
Plugin developers can add app lifecycle hooks by implementing the `get_app_lifecycle_hooks()` function in their library plugin that returns a list of `AppLifecycleHook` objects that will be executed before or after an app launches.
Additionally, this change includes updates to the `LaunchManager` to use the modern way (gamescope v3.16.14+) …
=> feat(Launch): add app lifecycle implementation and better handling of steam

core/systems/input/focus_group.gd, core/systems/input/input_manager.gd, core/systems/input/overlay_mode_input_manager.gd
In some cases, a user may find themselves in a position where no UI element is currently focused and will be unable to use the joystick or d-pad to regain control. This change updates the `InputManager` to find a focusable node and focus it if a direction is pressed and nothing is focused, ensuring that the user will always be able to use gamepad controls.
Because the logic already exists for recursively finding a focusable node in `FocusGroup`, this change updates the `find_focusable` method in that class to be a public static method so it can be used elsewhere.
=> fix(Focus): re-focus ui if focus is lost but a direction is pressed
